modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="https://github.com/Rebel459/bloom/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}-neoforge"
displayName="${mod_name}"
displayURL="https://github.com/Rebel459/bloom"
logoFile="assets/icon.png"
authors="Rebel459, Sierra, King, Castiel, DigitalPear, Zhen, AViewFromTheTop"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${neoforge_minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="unified"
type="required"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"

[[dependencies.${mod_id}]]
modId="biolith"
type="required"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config = "bloom.mixins.json"
[[mixins]]
config = "bloom-neoforge.mixins.json"
